import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


import { Route, Routes } from 'react-router-dom';

const Login = require('./pages/Login');
const Lobby = require('./pages/Lobby');
const Game = require('./pages/Game');
const SignOut = require('./components/SignOut');
const RedirectToLobby = require('./components/RedirectToLobby');

import './Layout.css'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SignOut />
        <RedirectToLobby />
        <Routes>
            <Route path='/' element={<Login />} />
            <Route path='/lobby' element={<Lobby />} />
            <Route path='/lobby/:lobbyCode' element={<Game />} />
        </Routes>
      </body>
    </html>
  );
}
